### ISSUE TITLE
Is there any way to turn on the TV?

### ISSUE THREAD

**Issue by sujeetpillai** [msloth/lgtv.js#21]
The app seems to be able to do it but I don't see any function in this code. Does a Wake-on-lan do it?

**Comment by msloth** [comment]
I think a wake-on-lan work but haven't tried it. If you do, please let me know how it went. :) thanks

**Comment by sujeetpillai** [comment]
I tried a wake-on-lan from a mobile app but it didn't work. I'm guessing wake on lan only works on ethernet ports and not wi-fi right?
