### ISSUE TITLE
discover_ip returns 1st udp device

### ISSUE THREAD

**Issue by blia** [msloth/lgtv.js#23]
https://github.com/msloth/lgtv.js/blob/4b6480711fb5f49c6efc4c1a44f0ec3d2898d561/index.js#L236
This code isn't working, because in JS `-1` is `true`. So any device passes this condition.

This code works for me:
```
if (message.includes("Server: WebOS")) {
  ...
}
```

**Comment by msloth** [comment]
Ha! Thanks!
