### ISSUE TITLE
how can I next/prev channel ?

### ISSUE THREAD

**Issue by berkaytheunicorn** [msloth/lgtv.js#6]
like in the title, how can I manage to do that ? is there a function for this or I need to calculate from channel list?

**Comment by msloth** [comment]
I'm unsure, haven't used this myself. There is currently no way with this lib except getting the channellist and enumerating that one.

**Comment by msloth** [comment]
I found in the ConnectSDK some additional endpoints, I'll integrate them soon. Meanwhile, if you would like to do it yourself, use:
`ssap://tv/channelUp` and `ssap://tv/channelDown`.

**Comment by berkaytheunicorn** [comment]
hmm thanks can you show me how can I trigger this ?

**Comment by msloth** [comment]
Not so helpful, but check the code and duplicate any of the existing similar functions, or wait for me to build it.

**Comment by msloth** [comment]
Latest version includes functions for next/prev channel. Closing.
